---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin
  labels:
    app: goviolin
spec:
  selector:
    matchLabels:
      app: goviolin
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: goviolin
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: goviolin
        image: geekahmed/goviolin
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            scheme: HTTP
            port: 8080
          successThreshold: 1
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: "service-goviolin"
spec:
  selector:
    app: goviolin
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080